students/urls.py
from django.conf.urls import url
from . import views
app_name = 'students'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.new_student, name='new_student'),
    url(r'^new/attendance/$', views.new_attendance, name='new_attendance'),
    url(r'^new/interview/$', views.new_interview, name='new_interview'),
    url(r'^new/experience/$', views.new_experience, name='new_experience'),
    url(r'^new/family/$', views.new_family, name='new_family'),
    url(r'^new/fujiyama/$', views.new_fujiyama, name='new_fujiyama'),
    url(r'^(?P<pk>[0-9]+)/detail/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/detail/attendance/$', views.attendance, name='attendance'),
    url(r'^(?P<pk>[0-9]+)/detail/interview/$', views.interview, name='interview'),
    url(r'^(?P<pk>[0-9]+)/detail/experience/$', views.experience, name='experience'),
    url(r'^(?P<pk>[0-9]+)/detail/family/$', views.family, name='family'),
    url(r'^(?P<pk>[0-9]+)/detail/fujiyama/$', views.fujiyama, name='fujiyama'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.edit_student, name='edit_student'),
    url(r'^(?P<pk>[0-9]+)/edit/interview/$', views.edit_interview, name='edit_interview'),
]

students_database/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^students/', include('students.urls')),
]

students/models.py
from django.db import models
# Create your models here.
class Student(models.Model):

	english_name = models.CharField(max_length=200)
	khmer_name = models.CharField(max_length=200, blank=True)
	japanese_name = models.CharField(max_length=200, blank=True)
	nationality = models.CharField(max_length=50)
	place_of_birth = models.CharField(max_length=200)
	card_id = models.CharField(max_length=100, blank=True)
	khmer_salary = models.FloatField(max_length=10, default=150, blank=True)
	EDU = (
		('Primary School','Primary School'),
		('Secondary School','Secondary School'),
		('High School','High School'),
		('University','University'),
		('Vocation School', 'Vocation Shool'),
		('Traning School','Traning School'),
		)
	education = models.CharField(max_length=200, choices=EDU)
	date_of_birth = models.DateField(auto_now=False, auto_now_add=False)
	age = models.PositiveIntegerField(default=0)
	GENDER = (
			('Male','Male'),
			('Female','Female'),
		)
	gender = models.CharField(max_length=200,choices=GENDER)
	state_of_healt = models.CharField(max_length=20, blank=True)
	blood_type = models.CharField(max_length=20, blank=True)
	vision = models.CharField(max_length=50, blank=True)
	interest = models.CharField(max_length=50, blank=True)
	year_of_experience = models.IntegerField(default=0)
	MARRIED = (
			('Yes','Yes'),
			('No','No'),
		)
	married = models.CharField(max_length=50, choices=MARRIED)
	position = models.CharField(max_length=50, blank=True)
	behavior = models.CharField(max_length=50, blank=True)
	went_to_japan = models.CharField(max_length=50, choices=MARRIED)
	japanese_conversation = models.CharField(max_length=50, choices=MARRIED)
	height = models.CharField(max_length=50, blank=True)
	weight = models.CharField(max_length=50, blank=True)
	current_address = models.CharField(max_length=200)
	
	REASON = (
		('Increase Revenue','Increase Revenue'),
		('Respect to parents','Respect to parents'),
		('Improve Living','Improve Living'),
		('Education','Education'),
		('Other Reason','Other Reason'),
		)
	reason = models.CharField(max_length=255, choices=REASON)
	arrang_money = models.TextField(max_length=255, blank=True)
	COMPANY=(
		('Company 168','Company 168'),
		('Phnom Penh Thmey','Phnom Penh Thmey'),
		('CL Supply Company','CL Supply COMPANY'),
		('Other Company','Other Company'),
		)
	sending_company = models.CharField(max_length=200, choices=COMPANY)
	LEVEL = (
		('level','level'),
		('N5','N5'),
		('N4','N4'),
		('N3','N3'),
		('N2','N2'),
		('N1','N1'),
	)
	japanese_level = models.CharField(max_length=50, choices=LEVEL)
	field_of_work = models.CharField(max_length=50, blank=True)
	date_go_japan = models.DateField(auto_now_add=False, auto_now=False, blank=True)
	prefecture = models.CharField(max_length=50, blank=True)
	zip_code = models.CharField(max_length=50, blank=True)
	address_in_japan = models.CharField(max_length=200)
	
	grammer_level = models.CharField(max_length=200, blank=True)
	idiom_level = models.CharField(max_length=200, blank=True)
	conversation_level = models.CharField(max_length=200, blank=True)
	life_attitude = models.CharField(max_length=200, blank=True)
	course_type = models.CharField(max_length=100, blank=True)
	last_peroid_of_study = models.DateField(auto_now=False, auto_now_add=False, blank=True)
	university_name = models.CharField(max_length=200, blank=True)
	subject_name = models.CharField(max_length=100, blank=True)
	teacher_name = models.CharField(max_length=50, blank=True)
	book_type = models.CharField(max_length=50, blank=True)
	start_date = models.DateField(blank=True)
	end_date = models.DateField(blank=True)
	status = models.CharField(max_length=50, blank=True)
	description = models.CharField(max_length=255, blank=True)
	
	admin_name = models.CharField(max_length=50, blank=True)
	email_address = models.EmailField(max_length=255, blank=True)
	phone_number = models.CharField(max_length=255, blank=True)
	
	def __str__(self):
		return self.english_name

class Experience(models.Model):
	
	student = models.ForeignKey(Student, on_delete=models.CASCADE)	
	last_peroid_of_working = models.DateField(auto_now=False,auto_now_add=False, blank=True)
	company_name = models.CharField(max_length=100, blank=True)
	position = models.CharField(max_length=50, blank=True)
	
	def __str__(self):
		return "Company name :"+self.company_name

class Family(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	name = models.CharField(max_length=50)
	age = models.PositiveIntegerField()
	job = models.CharField(max_length=50)
	position = models.CharField(max_length=50)
	status = models.CharField(max_length=50)
	def __str__(self):
		return 'Name: '+self.name +', Postion: '+self.position

class Attendance(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	date_study = models.DateField()
	status = models.CharField(max_length=100, blank=True)
	description = models.CharField(max_length=200, blank=True)

	def __str__(self):
		return "Date : " + self.date_study.strftime("%d-%m-%Y")

class Interview(models.Model):

	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	interview_date = models.DateField(blank=True)
	interview_type = models.CharField(max_length=100, blank=True)
	company_name = models.CharField(max_length=200, blank=True)
	status = models.CharField(max_length=50, blank=True)
	job_history = models.CharField(max_length=200, blank=True)
	certificate = models.CharField(max_length=200, blank=True)
	certificate_file = models.FileField(blank=True)

	def __str__(self):
		return " Interview status :"+ self.status

class Fujiyama(models.Model):

	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	entry_date = models.DateField(auto_now=False,auto_now_add=False)
	score = models.FloatField(default=0)
	player_learn_detail = models.CharField(max_length=200)
	correct_answer = models.IntegerField(default=0)
	duration = models.DurationField()
	email = models.EmailField(max_length=250)
	incorrect_answer = models.IntegerField(default=0)
	login_source = models.CharField(max_length=200)
	phone_number = models.CharField(max_length=20)
	status = models.CharField(max_length=200)

	def __str__(self):
		return "Registration type :" + self.login_source

students/forms.py
from django.forms import ModelForm
from .models import *

class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

class AttendanceForm(ModelForm):
	class Meta:
		model = Attendance
		fields = '__all__'


class InterviewForm(ModelForm):
	class Meta:
		model = Interview
		fields = '__all__'

class FujiyamaForm(ModelForm):
	class Meta:
		model = Fujiyama
		fields = '__all__'
		
class FamilyForm(ModelForm):
	class Meta:
		model = Family
		fields = '__all__'
					
class ExperienceForm(ModelForm):
	class Meta:
		model = Experience
		fields = '__all__'

students/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import *
from .forms import *

# Create your views here.
def index(request):
    students = Student.objects.all()
    context = { 'students': students }
    return render(request, 'students/index.html', context)

def detail(request,pk=None):
    student = Student.objects.get(pk=pk)
    context = {'student': student }
    return render(request, 'students/detail.html', context)

def attendance(request, pk=None):
    student = get_object_or_404(Student, pk=pk)
    attendances = get_list_or_404(Attendance, student = student)
    context = { 'student' : student, 'attendances' : attendances }
    return render(request, 'students/attendance.html', context )

def interview(request, pk=None):
    student = get_object_or_404(Student, pk=pk)
    interviews = get_list_or_404(Interview, student = student)
    context = { 'student' : student, 'interviews' : interviews }
    return render(request, 'students/interview.html', context )
    
def experience(request, pk=None):
    student = get_object_or_404(Student, pk=pk)
    experiences = get_list_or_404(Experience, student = student)
    context = { 'student' : student, 'experiences' : experiences }
    return render(request, 'students/experience.html', context )

def family(request, pk=None):
    student = get_object_or_404(Student, pk=pk)
    families = get_list_or_404(Family, student = student)
    context = { 'student' : student, 'families' : families }
    return render(request, 'students/family.html', context )

def fujiyama(request, pk=None):
    student = get_object_or_404(Student, pk=pk)
    fujiyamas = get_list_or_404(Fujiyama, student = student)
    context = { 'student' : student, 'fujiyamas' : fujiyamas }
    return render(request, 'students/fujiyama.html', context )
    # NEW STUDENT INFORMATION
def new_student(request):
    if request.method == "POST":
        formS = StudentForm(request.POST)
        context = { 'formS': formS }
        if formS.is_valid():
            formS = formS.save()
            return HttpResponseRedirect(reverse('students:index'))
        else:
            return render(request, 'students/new_student.html', context)
    else:
        formS = StudentForm()
        context = { 'formS' : formS }
        return render(request, 'students/new_student.html', context)

def new_attendance(request):
    if request.method == "POST":
        formA = AttendanceForm(request.POST)
        context = { 'formA': formA }
        if formA.is_valid():
            formA = formA.save()
            return HttpResponseRedirect(reverse('students:index'))
        else:
            return render(request, 'students/new_attendance.html', context)
    else:
        formA = AttendanceForm()
        context = { 'formA' : formA }
        return render(request, 'students/new_attendance.html', context)

def new_interview(request):
    if request.method == "POST":
        formI = InterviewForm(request.POST)
        context = { 'formI': formI }
        if formI.is_valid():
            formI = formI.save()
            return HttpResponseRedirect(reverse('students:index'))
        else:
            return render(request, 'students/new_interview.html', context)
    else:
        formI = InterviewForm()
        context = { 'formI' : formI }
        return render(request, 'students/new_interview.html', context)
        
def new_experience(request):
    if request.method == "POST":
        formE = ExperienceForm(request.POST)
        context = { 'formE': formE }
        if formE.is_valid():
            formE = formE.save()
            return HttpResponseRedirect(reverse('students:index'))
        else:
            return render(request, 'students/new_experience.html', context)
    else:
        formE = ExperienceForm()
        context = { 'formE' : formE }
        return render(request, 'students/new_experience.html', context)

def new_family(request):
    if request.method == "POST":
        formF= FamilyForm(request.POST)
        context = { 'formF': formF }
        if formF.is_valid():
            formF = formF.save()
            return HttpResponseRedirect(reverse('students:index'))
        else:
            return render(request, 'students/new_family.html', context)
    else:
        formF = FamilyForm()
        context = { 'formF' : formF }
        return render(request, 'students/new_family.html', context)
        
def new_fujiyama(request):
    if request.method == "POST":
        formFu= FujiyamaForm(request.POST)
        context = { 'formFu': formFu }
        if formFu.is_valid():
            formFu = formFu.save()
            return HttpResponseRedirect(reverse('students:index'))
        else:
            return render(request, 'students/new_fujiyama.html', context)
    else:
        formFu = FamilyForm()
        context = { 'formFu' : formFu }
        return render(request, 'students/new_fujiyama.html', context)
        
# EDIT PAGE ====================================================================
def edit_student(request, pk=None):
    student = get_object_or_404(Student,pk=pk)
    if request.method == "POST":
        formS = StudentForm(request.POST, instance=student)
        context = { 'formS': formS }
        if formS.is_valid():
            formS = formS.save()
            return HttpResponseRedirect(reverse('students:index'))
        else:
            return render(request, 'students/edit_student.html', context)
    else:
        formS = StudentForm(instance=student)
        context = { 'formS' : formS }
        return render(request, 'students/edit_student.html', context)
    
def edit_interview(request, pk=None):
    student = get_object_or_404(Student,pk=pk)
    if request.method == "POST":
        formI = InterviewForm(request.POST, instance=student)
        context = { 'formI': formI }
        if formI.is_valid():
            formI = formI.save()
            return HttpResponseRedirect(reverse('students:index'))
        else:
            return render(request, 'students/edit_interview.html', context)
    else:
        
        formI = InterviewForm(instance=student)
        context = { 'formI' : formI }
        return render(request, 'students/edit_interview.html', context)

students/templates/students/detail.html
{% extends 'students/base.html' %}

{% block content %}

<div class="container">
    <br>
    <br>
    {% if student %}
        <h3 class="text-primary"><u>Student Information Detail</u></h3><br>
        <a href="{% url 'students:edit_student' student.id %}">Update Student |</a>
        <br>
        <div class="row bg-success text-white">
          <br>
          <div class="col"><p><br>English Name : "{{ student.english_name }}"</p></div>
          <div class="col"><p><br>Khmer Name : "{{ student.khmer_name }}"</p></div>
          <div class="col"><p><br>Japanese Name : "{{ student.japanese_name }}"</p></div>
        </div>
        <div class="row bg-success text-white">
          <br>
          <div class="col"><p>Nationality : "{{ student.nationality }}"</p></div>
          <div class="col"><p>Place Of Birth : "{{ student.place_of_birth }}"</p></div>
          <div class="col"><p>Card id : "{{ student.card_id }}"</p></div>
        </div>
        <div class="row bg-success text-white">
          <br>
          <div class="col"><p>Cambodia Salary : "${{ student.khmer_salary }} "</p></div>
          <div class="col"><p>Education Level : "{{ student.education }}"</p></div>
          <div class="col"><p>Birth Day : "{{ student.date_of_birth }}"</p></div>
        </div>
        <div class="row bg-success text-white">
          <br>
          <div class="col"><p>Age : "{{ student.age }}"</p></div>
          <div class="col"><p>Gender : "{{ student.gender }}"</p></div>
          <div class="col"><p>State Of Health : "{{ student.state_of_healt }}"</p></div>
        </div>
        
        <div>
        <br>
        <a href="{% url 'students:attendance' student.id %}">Check Attendance |</a>
        <a href="{% url 'students:new_attendance' %}">New attendance </a><br>
        <a href="{% url 'students:interview' student.id %}">Check Interview |</a>
        <a href="{% url 'students:new_interview' %}">New Interview </a><br>
        <a href="{% url 'students:experience' student.id %}">Check Experience |</a>
        <a href="{% url 'students:new_experience' %}">New Experience </a><br>
        <a href="{% url 'students:family' student.id %}">Check Family |</a>
        <a href="{% url 'students:new_family' %}">New Family Member</a><br>
        <a href="{% url 'students:fujiyama' student.id %}">Check Fujiyama Program |</a>
        <a href="{% url 'students:new_fujiyama' %}">New Fujiyama</a><br>
        <p><a href="{% url 'students:index' %}">Students list</a></p> 
        </div>
    {% endif %}
</div>
{% endblock %}

students/templates/students/edit_family.html
{% extends 'students/base.html' %}

{% block content %}
	<div class="container">
	<br>
	<h3 class="text-primary"><u>Updating FAMILY data</u></h3>
	<br>
	<form method="POST" action="" class="" >
        {% csrf_token %}
        {{ formf.as_p }}
        <p>=================================================================</p>
        <!-- {{ formA.as_p }} -->
        <button type="submit" class="save btn btn-success">Update Data</button>
    </form>
    <br>
    <br>
	</div>
{% endblock %}

students/templates/students/edit_fujiyama.html
{% extends 'students/base.html' %}

{% block content %}
	<div class="container">
	<br>
	<h3 class="text-primary"><u>Updating fujiyama data</u></h3>
	<br>
	<form method="POST" action="" class="" >
        {% csrf_token %}
        {{ formFu.as_p }}
        <p>=================================================================</p>
        <!-- {{ formA.as_p }} -->
        <button type="submit" class="save btn btn-success">Update Data</button>
    </form>
    <br>
    <br>
	</div>
{% endblock %}

students/templates/students/edit_interview.html
{% extends 'students/base.html' %}

{% block content %}
	<div class="container">
	<br>
	<h3 class="text-primary"><u>Updating interviews</u></h3>
	<br>
	<form method="POST" action="" class="" >
        {% csrf_token %}
        {{ formI.as_p }}
        <p>=================================================================</p>
        <!-- {{ formA.as_p }} -->
        <button type="submit" class="save btn btn-success">Update Data</button>
    </form>
    <br>
    <br>
	</div>
{% endblock %}

students/templates/students/edit_student.html
{% extends 'students/base.html' %}

{% block content %}
	<div class="container">
	<br>
	<h3 class="text-primary"><u>Updating student information</u></h3>
	<br>
	<form method="POST" action="" class="" >
        {% csrf_token %}
        {{ formS.as_p }}
        <p>=================================================================</p>
        <!-- {{ formA.as_p }} -->
        <button type="submit" class="save btn btn-success">Update Data</button>
    </form>
    <br>
    <br>
	</div>
{% endblock %}

students/templates/students/experience.html
{% extends 'students/base.html' %}

{% block content %}
<br><br>
   <div class="container">
      {% if student %}
         {% if experiences %}
            <h2 style="color: #0066ff;"><u>Experience</u></h2>
            <h3 style="text-align: center; "><b style="color: #0066ff;">{{ student.english_name }}</b></h2><br>
            <h4><a href="{% url 'students:new_interview' %}">New Experience</a></h4><br>
               <table class="table table-hover table-sm table-striped table-responsive-sm " style="text-align: center;">
                  <thead class="bg-success" style="color: white; height: 30px;">
                     <tr>
                        <th>Last Peroid of Working</th>
                        <th>Position</th>
                        <th>Company Name</th>  
                     </tr>
                  </thead>
                  <tbody class=" table-sm table-hover" >
                     {% for experience in experiences %}
                     <tr class=" table-sm table-hover" >
                        <td>{{ experience.last_peroid_of_working }}</td>
                        <td>{{ experience.position }}</td>
                        <td>{{ experience.company_name }}</td>
                     </tr>
                     {% endfor %}
                  </tbody>
               </table>
               <br>
               <a href="{% url 'students:index' %}">Students list</a> 
         {% else %}
                <p>No Experience are available.</p>
         {% endif %}
      {% else %}
          <p>No Student are available.</p>
      {% endif %}
      </div>
{% endblock %}

students/templates/students/family.html
{% extends 'students/base.html' %}

{% block content %}
<br><br>
   <div class="container">
      {% if student %}
         {% if families %}
            <h2 style="color: #0066ff;"><u>Family Member</u></h2>
            <h3 style="text-align: center; "><b style="color: #0066ff;">{{ student.english_name }}</b></h2><br>
            <h4><a href="{% url 'students:new_interview' %}">New Family Member</a></h4><br>
               <table class="table table-hover table-sm table-striped table-responsive-sm " style="text-align: center;">
                  <thead class="bg-success" style="color: white; height: 30px;">
                     <tr>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Position</th>  
                        <th>Occupation</th>
                        <th>Status</th>
                     </tr>
                  </thead>
                  <tbody class=" table-sm table-hover" >
                     {% for family in families %}
                     <tr class=" table-sm table-hover" >
                        <td>{{ family.name }}</td>
                        <td>{{ family.age }}</td>
                        <td>{{ family.position }}</td>
                        <td>{{ family.job }}</td>
                        <td>{{ family.status }}</td>
                     </tr>
                     {% endfor %}
                  </tbody>
               </table>
               <br>
               <a href="{% url 'students:index' %}">Students list</a> 
         {% else %}
                <p>No Experience are available.</p>
         {% endif %}
      {% else %}
          <p>No Student are available.</p>
      {% endif %}
      </div>
{% endblock %}

students/templates/students/fujiyama.html
{% extends 'students/base.html' %}

{% block content %}
<br><br>
   <div class="container">
      {% if student %}
         {% if fujiyamas %}
            <h2 style="color: #0066ff;"><u>Fujiyama Program</u></h2>
            <h3 style="text-align: center; "><b style="color: #0066ff;">{{ student.english_name }}</b></h2><br>
            <h4><a href="{% url 'students:new_interview' %}">New Fujiyama Program</a></h4><br>
               <table class="table table-hover table-sm table-striped table-responsive-sm " style="text-align: center;">
                  <thead class="bg-success" style="color: white; height: 30px;">
                     <tr>
                        <th>Entry Date</th>
                        <th>Score</th>
                        <th>Player</th>  
                        <th>Correct Answer</th>
                        <th>Incorrect Answer</th>  
                        <th>Duration</th>  
                        <th>Email</th>
                        <th>Phone Number</th>
                        <th>Login Source</th>
                        <th>Status</th>
                     </tr>
                  </thead>
                  <tbody class=" table-sm table-hover" >
                     {% for fujiyama in fujiyamas %}
                     <tr class=" table-sm table-hover" >
                        <td>{{ fujiyama.entry_date }}</td>
                        <td>{{ fujiyama.score }}</td>
                        <td>{{ fujiyama.player_learn_detail }}</td>
                        <td>{{ fujiyama.correct_answer }}</td>
                        <td>{{ fujiyama.incorrect_answer }}</td>
                        <td>{{ fujiyama.duration }}</td>
                        <td>{{ fujiyama.email }}</td>
                        <td>{{ fujiyama.phone_number }}</td>
                        <td>{{ fujiyama.login_source }}</td>
                        <td>{{ fujiyama.status }}</td>
                     </tr>
                     {% endfor %}
                  </tbody>
               </table>
               <br>
               <a href="{% url 'students:index' %}">Students list</a> 
         {% else %}
                <p>No Experience are available.</p>
         {% endif %}
      {% else %}
          <p>No Student are available.</p>
      {% endif %}
      </div>
{% endblock %}

students/templates/students/index.html
{% extends 'students/base.html' %}

{% block content %}
				<div class="container">
					<div>
					<br>
					<h2><i style="color: #0066ff;">Students list</i></h2>
				    <br>
				    <table class="table table-hover table-sm table-striped table-responsive-sm " style="text-align: center;">
				    	<thead class="bg-primary" style="color: white; height: 30px;">
				    		<tr>
				    			<th>ID</th>
				    			<th>Name</th>
				    			<th>Gender</th>
				    			<th>Age</th>
				    			<th>Hometown</th>
				    			<th>Sending Company</th>
				    			<th>Start Date</th>
				    			<th>Japanese</th>
				    			<th>Contact</th>
				    			<th>Detail</th>
				    		</tr>
				    	</thead >
				    	<tbody class="table-hover">
				    	{% if students %}
				    	{% for student in students %}
				    		<tr class=" table-xm table-hover" >
				    			<td>{{ student.id }}</td>
				    			<td><strong><a href="{% url 'students:detail' student.id %}">{{ student.english_name }}</a></strong></td>
				    			<td>{{ student.gender }}</td>
				    			<td>{{ student.age }}</td>
				    			<td>{{ student.place_of_birth }}</td>
				    			<td>{{ student.sending_company }}</td>
				    			<td>{{ student.start_date }}</td>
				    			<td>{{ student.japanese_level }}</td>
				    			<td>{{ student.phone_number }}</td>
				    			<td><a class="btn btn-sm btn-primary"  href="{% url 'students:detail' student.id %}">detail</a></td>
				    		</tr>
				    	{% endfor %}
						{% else %}
						    <p>No student are available.</p>
						{% endif %}
				    	</tbody>
				    </table>
					</div>
				</div>
{% endblock %}

students/templates/students/new_attendance.html
{% extends 'students/base.html' %}

{% block content %}
	<div class="container">
	<br>
	<h3 class="text-primary"><u>Input Attendance </u></h3>
	<br>
	<form method="POST" action="" class="" >
        {% csrf_token %}
        {{ formA.as_p }}
        <p>=================================================================</p>
        <!-- {{ formA.as_p }} -->
        <button type="submit" class="save btn btn-success">Save Data</button>
    </form>
    <br>
    <br>
	</div>
{% endblock %}

students/templates/students/new_experience.html
{% extends 'students/base.html' %}
{% block content %}
	<div class="container">
	<br>
	<h3 class="text-primary"><u>Input Experience </u></h3>
	<br>
	<form method="POST" action="" class="" >
        {% csrf_token %}
        {{ formE.as_p }}
        <p>=================================================================</p>
        <!-- {{ formA.as_p }} -->
        <button type="submit" class="save btn btn-success">Save Data</button>
    </form>
    <br>
    <br>
	</div>
{% endblock %}

students/templates/students/new_fujiyama.html
{% extends 'students/base.html' %}

{% block content %}
	<div class="container">
	<br>
	<h3 class="text-primary"><u>Input Fujiyama Data </u></h3>
	<br>
	<form method="POST" action="" class="" >
        {% csrf_token %}
        {{ formFu.as_p }}
        <p>=================================================================</p>
        <!-- {{ formA.as_p }} -->
        <button type="submit" class="save btn btn-success">Save Data</button>
    </form>
    <br>
    <br>
	</div>
{% endblock %}

students/templates/students/new_interview.html
{% extends 'students/base.html' %}

{% block content %}
	<div class="container">
	<br>
	<h3 class="text-primary"><u>Input Interview </u></h3>
	<br>
	<form method="POST" action="" class="" >
        {% csrf_token %}
        {{ formI.as_p }}
        <p>=================================================================</p>
        <!-- {{ formA.as_p }} -->
        <button type="submit" class="save btn btn-success">Save Data</button>
    </form>
    <br>
    <br>
	</div>
{% endblock %}

students/templates/students/new_student.html
{% extends 'students/base.html' %}

{% block content %}
	<div class="container">
	<br>
	<h3 class="text-primary"><u>Registration New Student</u></h3>
	<br>
	<form method="POST" action="" class="" >
        {% csrf_token %}
        {{ formS.as_p }}
        <p>=================================================================</p>
        <!-- {{ formA.as_p }} -->
        <a href="{% url 'students:index' students.id %}"><button type="submit" class="save btn btn-success">Save Data</button></a> 
    </form>
    <br>
    <br>
	</div>
{% endblock %}